apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # base65 generated string out of 'mongouser'
  mongo-user: bW9uZ291c2Vy
  # base65 generated string out of 'mongopassword'
  mongo-password: bW9uZ29wYXNzd29yZA==